#!/bin/bash
#PBS -l nodes=1:ppn=16:dc2,walltime=00:20:00
#PBS -N app-MapMRI
#PBS -V

#for local testing
if [ -z $SERVICE_DIR ]; then export SERVICE_DIR=`pwd`; fi

[ $PBS_O_WORKDIR ] && cd $PBS_O_WORKDIR

echo "running main"
time python -u $SERVICE_DIR/main.py

ret=$?
if [ $ret -ne 0 ]; then
    echo "main.py failed"
    echo $ret > finished
    exit $ret
fi

count=$(ls tract1/*.tck | wc -l)
if [ $count -eq 4 ];
then
	echo 0 > finished
else
	echo "files missing"
	echo 1 > finished
	exit 1
fi
